### PR TITLE
fix: create color palette based on display's supported colors

### LINKED ISSUE #38: Palette colors should be changed according to the display
https://github.com/user-attachments/assets/ac9062ce-9659-4349-a590-52fbbdcee49d

Red Color should not be present in the black and white e ink display

### PR DESCRIPTION
**Pull request by Vishveshwara**
Fixes #38 

Screen Recording:

https://github.com/user-attachments/assets/f2e9bd84-8752-4d9a-bbb4-ff4425312b9e

- Used a provider to use the palette displayed in the epd class
- changed initialisation color for painting from red to black

## Summary by Sourcery

Introduce and wire up ColorPaletteProvider to dynamically feed display-specific color palettes into the color picker and default the initial paint color to black.

New Features:
- Introduce ColorPaletteProvider to manage and update the active color palette based on the selected display.

Bug Fixes:
- Change the default initial paint color from red to black across editors.

Enhancements:
- Wire up DisplaySelectionScreen to populate the provider with the chosen e-paper display’s supported colors.
- Refactor ColorPickerCustom and BottomBarCustom to consume the dynamic palette from the provider and remove hard-coded initialColor parameters.
- Register ColorPaletteProvider in the app’s MultiProvider setup.

### CODE REVIEW

File: lib/main.dart [hunk 1]
```diff
@@ -1,11 +1,13 @@
 import 'package:flutter/material.dart';
 import 'package:magic_epaper_app/provider/image_loader.dart';
+import 'package:magic_epaper_app/provider/color_palette_provider.dart';
 import 'package:provider/provider.dart';
 import 'package:magic_epaper_app/view/display_selection_screen.dart';
 
 void main() {
   runApp(MultiProvider(providers: [
     ChangeNotifierProvider(create: (context) => ImageLoader()),
+    ChangeNotifierProvider(create: (context) => ColorPaletteProvider()),
```
Comment (AsCress) [inline lib/main.dart]: Do we need to add this as a `ChangeNotiferProvider` for the whole app if we're using this only in a certain screen ?

Comment (Vishveshwara) [reply lib/main.dart]: Hey @AsCress , i am planning to add color channel adjustments, to control red , black , white threshold , so this provider should work for image_editor.dart as well, where i am planning to add it.

Comment (AsCress) [reply lib/main.dart]: @Vishveshwara Then maybe inject it using `getIt` ?

Comment (Vishveshwara) [reply lib/main.dart]: okay , I will try using getIt and update this pr

Comment (Vishveshwara) [reply lib/main.dart]: I have implemented it using getIt below, since i am updating the colors of the ColorPaletteProvider in only the display_selection_screen , what is the actual benifit using getIt ? since provider can do the same function, can you please explain this

File: lib/main.dart [hunk 2]
```diff
@@ -1,11 +1,16 @@
...
 import 'package:magic_epaper_app/provider/image_loader.dart';
+import 'package:magic_epaper_app/provider/color_palette_provider.dart';
 import 'package:provider/provider.dart';
 import 'package:magic_epaper_app/view/display_selection_screen.dart';
 
 void main() {
+  setupLocator();
   runApp(MultiProvider(providers: [
     ChangeNotifierProvider(create: (context) => ImageLoader()),
+    ChangeNotifierProvider<ColorPaletteProvider>(
```
Comment (AsCress) [inline lib/main.dart]: @Vishveshwara Nicely implemented `getIt`! Good job on that ! However, the whole purpose of using `getIt` is that you can inject that particular dependency wherever you want, while still maintaining a single instance of it in your app. We don't unleash it's potential if we just inject it in the beginning for the whole app, this is similar to what you were doing before.
Just inject it wherever required. Let's say you want to use it as a `ChangeNotifierProvider` for `display_selection_screen.dart` and `image_editor.dart`, register that `ChangeNotifierProvider` using `MultiProvider` for those screens only, and fetch it using `getIt`.
I'll make myself more clear here, wrap those both screens with this:
`
MultiProvider(providers: [ChangeNotifierProvider<ColorPaletteProvider>(
create: (context) => getIt<ColorPaletteProvider>())
,], child: ... ));
`
instead of wrapping the whole `MyApp()` function with it.
Let me know if you still didn't understand anything here !

**Comment by AsCress** [comment]
If you were using the dependency only for one screen, then you could also simply create a new instance of your provider for that screen only (since it is something required only for that screen and not the whole app), without using `getIt`. However, you mentioned that you're gonna use your provider in multiple screens, then `getIt` provides a nice way to handle that.

File: lib/main.dart (hunk 2 above)
Comment (Vishveshwara) [reply lib/main.dart]: Hey @AsCress thanks for the explanation , I understand it , let me try implementing it first if I run into any issues i will mention you.

**Comment by Vishveshwara** [comment]
@AsCress i have used

```
return ChangeNotifierProvider<ColorPaletteProvider>(
        create: (_) => getIt<ColorPaletteProvider>(),
        builder: (context, child) {
```
since i was getting an error with the method you had suggested and 

I have used the below code to update the colors in color_picker.dart

`final List<Color> _colors = getIt<ColorPaletteProvider>().colors;`

Is this fine?
