### PR TITLE
fix: fixed sizing for multiple displays 

### LINKED ISSUE #72: Adjust user flow for different ePaper sizes
- Currently the Preview Image in image_list.dart is a predefined height of 200 px and takes the width of the entire display
- the pro_image_editor cavas has hardcoded canvas size

### PR DESCRIPTION
**Pull request by Vishveshwara**
Fixes #72 

- Fixed Hardcoded values in the editor by passing the epd's height and width
- Fixed the filter screen by maintaining aspect ratio of the epd in preview
- If epd's display is greater than the phone's width or height , it will use the max size possible maintaining the aspect ratio

Screen Recording:
I have changed the Black/White display's height and width to show how the app will adjust

https://github.com/user-attachments/assets/70d6c9e4-099f-445c-b527-7dea37d2de2c

For 88 x 184

WhatsApp Image 2025-06-24 at 18 08 51_3bf92a7b

WhatsApp Image 2025-06-24 at 18 11 42_2a4bbec9

WhatsApp Image 2025-06-24 at 18 08 52_3a95d781

## Summary by Sourcery

Fix display sizing across editor and preview screens by computing canvas dimensions dynamically from the EPD’s width and height, maintaining aspect ratio and fitting within device constraints.

New Features:
- Add width and height parameters to the movable background editor for dynamic sizing based on EPD dimensions
- Introduce a loader that resizes the whiteboard background image to the computed canvas dimensions before editing

Bug Fixes:
- Fix hardcoded canvas dimensions in the editor to correctly scale for larger EPD displays
- Ensure filter preview and flipped image widgets maintain the EPD aspect ratio and fit within constrained bounds

Enhancements:
- Replace fixed 240×416 sizes with computed width/height fields in the editor
- Use AspectRatio and ConstrainedBox in ImageList to preserve preview aspect ratio
- Adjust FilterCard styling, shadow opacity, border, and image quality settings

Chores:
- Remove unused transparent image creation code

### CODE REVIEW

File: lib/pro_image_editor/features/movable_background_image.dart [hunk 1]
```diff
@@ -335,174 +345,184 @@ class _MovableBackgroundImageExampleState
...
-                              child: Stack(
-                                fit: StackFit.expand,
-                                alignment: Alignment.center,
-                                children: <Widget>[
-                                  ...previousChildren,
-                                  if (currentChild != null) currentChild,
-                                ],
-                              ),
+        child: FutureBuilder<Uint8List>(
+          future: _loadAndResizeWhiteBoard(),
```
[the remark this answers is not in the document]
Comment (Vishveshwara) [reply lib/pro_image_editor/features/movable_background_image.dart:349]: Loading the white background first, don't need logic for other colors

File: lib/view/widget/image_list.dart [hunk 2]
```diff
@@ -177,7 +189,7 @@ class FilterCard extends StatelessWidget {
           boxShadow: isSelected
               ? [
                   BoxShadow(
-                    color: colorPrimary.withValues(alpha: .2),
+                    color: colorPrimary.withValues(alpha: .4),
```
[the remark this answers is not in the document]
Comment (Vishveshwara) [reply lib/view/widget/image_list.dart:192]: https://stackoverflow.com/questions/79284946/why-is-withopacity-deprecated-in-flutter-3-27-0-and-what-is-its-recommended-rep

withOpacity is getting deprecated, withValues and withAlpha are the suggested methods

**Review by Dhruv1797 — APPROVED** [review]

File: lib/pro_image_editor/features/movable_background_image.dart [hunk 3]
```diff
@@ -70,6 +76,24 @@ class _MovableBackgroundImageExampleState
     super.dispose();
   }
 
+  void _calculateCanvasDimensions(Size screenSize) {
+    final double targetAspectRatio = widget.width / widget.height;
+    final double availableWidth = screenSize.width - 32;
```
Comment (AsCress) [inline lib/pro_image_editor/features/movable_background_image.dart:81]: Is this and the line below meant for padding ?

Comment (Vishveshwara) [reply lib/pro_image_editor/features/movable_background_image.dart:81]: @AsCress not for padding exactly, it is for the canvas dimensions. It is getting the aspect ratio `final double targetAspectRatio = widget.width / widget.height;` and calculating the height and width of the canvas that is required based on the screenSize that is passed in this function.

Comment (AsCress) [reply lib/pro_image_editor/features/movable_background_image.dart:81]: @Vishveshwara Yeah, that I get it. I have marked line 81 only. Where is that number 32 coming from ?

Comment (Vishveshwara) [reply lib/pro_image_editor/features/movable_background_image.dart:81]: i don't want the canvas to go to the end of the screen , so yeah this line is for padding.

**Comment by Vishveshwara** [comment]
@AsCress can you please merge this PR if you have completed your review.
