### PR TITLE
fix: move the display's initial code to the app

### LINKED ISSUE #76: Move the display's initial code to the app
The firmware currently works with gdey037z03 ONLY. fossasia/magic-epaper-firmware#13

### PR DESCRIPTION
**Pull request by kienvo**
Fixes #76

## Summary by Sourcery

Abstract EPaper waveform handling and integrate it into the UC8253 driver, refactor the NFC Protocol to streamline tag communication, and relocate display initialization into the application to correct startup issues.

New Features:
- Introduce waveform abstraction (`Waveform` and `Lut`) and add `QuickLut` implementation for the UC8253 driver
- Implement `init` and `setlut` methods in `Uc8253` to manage panel initialization and LUT loading

Bug Fixes:
- Fix display startup sequence by relocating initial setup code to the app (fix #76)

Enhancements:
- Refactor `Protocol` to store `tagId` internally and remove redundant tagId parameters from NFC operations
- Simplify transceive/write flows and dynamic configuration commands in the Protocol
- Move display initialization (power on and panel settings) into the app by calling `epd.controller.init` before frame transmission

### CODE REVIEW

File: lib/util/epd/driver/uc8253.dart [hunk 1]
```diff
@@ -1,12 +1,142 @@
...
+    // VCOM_AND_DATA_INTERVAL_SETTING
+    await p.writeMsg(Uint8List.fromList([p.fw.epdCmd, 0x50]));
+    await p.writeMsg(Uint8List.fromList([p.fw.epdSend, 0xff, 0x0f]));
+
+    await p.writeMsg(Uint8List.fromList([p.fw.epdCmd, panelSetting]));
+    // 480x240, built-in LUTs
+    await p.writeMsg(Uint8List.fromList([p.fw.epdSend, 0xCF, 0x8D]));
+    // 480x240, LUTs from register
+    // await p.writeMsg(Uint8List.fromList([p.fw.epdSend, 0xEF, 0x8D]));
+    // await setlut(p, waveforms[0]);
```
Comment (marcnause) [inline lib/util/epd/driver/uc8253.dart:140]: Commented out code should usually not be committed. Is there a good reason to do it here?

Comment (kienvo) [reply lib/util/epd/driver/uc8253.dart:140]: This PR depends on #70 and has already been explained there.
